### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by littleheary** [YusinoMy/Rpcon#1]
# Rpcon/pkg                                                                                                      
pkg\wmiexec.go:27:15: execer.SetTargetBinding undefined (type *wmiexec.wmiExecer has no field or method SetTarget
Binding)                                                                                                         
pkg\wmiexec.go:40:13: execer.TargetRPCPort undefined (type *wmiexec.wmiExecer has no field or method TargetRPCPor
t)

**Comment by yusinomy** [comment]
那个是wmiexec包的问题 我改了下 你再编译试试
